/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.desgo.modelo;

/**
 *
 * @author egct
 */
public class DatosDescriptivosBloque_CCLote {
    Integer ID_DDB_CCLOTE;
    String NIVELPISO_DDB_CCLOTE;
    String CONDICIONFISICA_DDB_CCLOTE;
    String VALORCULTURAL_DDB_CCLOTE;
    String ESTADOCONSERVACION_DDB_CCLOTE;
    Integer ANIOCONSTRUCCION_DDB_CCLOTE;
    Integer ANIORESTAURACION_DDB_CCLOTE;
    float AREACONSTRUIDA_DDB_CCLOTE;
    String USOCONSTRUCTIVOPISO_DDB_CCLOTE;

    public DatosDescriptivosBloque_CCLote() {
    }

    public DatosDescriptivosBloque_CCLote(Integer ID_DDB_CCLOTE, String NIVELPISO_DDB_CCLOTE, String CONDICIONFISICA_DDB_CCLOTE, String VALORCULTURAL_DDB_CCLOTE, String ESTADOCONSERVACION_DDB_CCLOTE, Integer ANIOCONSTRUCCION_DDB_CCLOTE, Integer ANIORESTAURACION_DDB_CCLOTE, float AREACONSTRUIDA_DDB_CCLOTE, String USOCONSTRUCTIVOPISO_DDB_CCLOTE) {
        this.ID_DDB_CCLOTE = ID_DDB_CCLOTE;
        this.NIVELPISO_DDB_CCLOTE = NIVELPISO_DDB_CCLOTE;
        this.CONDICIONFISICA_DDB_CCLOTE = CONDICIONFISICA_DDB_CCLOTE;
        this.VALORCULTURAL_DDB_CCLOTE = VALORCULTURAL_DDB_CCLOTE;
        this.ESTADOCONSERVACION_DDB_CCLOTE = ESTADOCONSERVACION_DDB_CCLOTE;
        this.ANIOCONSTRUCCION_DDB_CCLOTE = ANIOCONSTRUCCION_DDB_CCLOTE;
        this.ANIORESTAURACION_DDB_CCLOTE = ANIORESTAURACION_DDB_CCLOTE;
        this.AREACONSTRUIDA_DDB_CCLOTE = AREACONSTRUIDA_DDB_CCLOTE;
        this.USOCONSTRUCTIVOPISO_DDB_CCLOTE = USOCONSTRUCTIVOPISO_DDB_CCLOTE;
    }

    public Integer getID_DDB_CCLOTE() {
        return ID_DDB_CCLOTE;
    }

    public void setID_DDB_CCLOTE(Integer ID_DDB_CCLOTE) {
        this.ID_DDB_CCLOTE = ID_DDB_CCLOTE;
    }

    public String getNIVELPISO_DDB_CCLOTE() {
        return NIVELPISO_DDB_CCLOTE;
    }

    public void setNIVELPISO_DDB_CCLOTE(String NIVELPISO_DDB_CCLOTE) {
        this.NIVELPISO_DDB_CCLOTE = NIVELPISO_DDB_CCLOTE;
    }

    public String getCONDICIONFISICA_DDB_CCLOTE() {
        return CONDICIONFISICA_DDB_CCLOTE;
    }

    public void setCONDICIONFISICA_DDB_CCLOTE(String CONDICIONFISICA_DDB_CCLOTE) {
        this.CONDICIONFISICA_DDB_CCLOTE = CONDICIONFISICA_DDB_CCLOTE;
    }

    public String getVALORCULTURAL_DDB_CCLOTE() {
        return VALORCULTURAL_DDB_CCLOTE;
    }

    public void setVALORCULTURAL_DDB_CCLOTE(String VALORCULTURAL_DDB_CCLOTE) {
        this.VALORCULTURAL_DDB_CCLOTE = VALORCULTURAL_DDB_CCLOTE;
    }

    public String getESTADOCONSERVACION_DDB_CCLOTE() {
        return ESTADOCONSERVACION_DDB_CCLOTE;
    }

    public void setESTADOCONSERVACION_DDB_CCLOTE(String ESTADOCONSERVACION_DDB_CCLOTE) {
        this.ESTADOCONSERVACION_DDB_CCLOTE = ESTADOCONSERVACION_DDB_CCLOTE;
    }

    public Integer getANIOCONSTRUCCION_DDB_CCLOTE() {
        return ANIOCONSTRUCCION_DDB_CCLOTE;
    }

    public void setANIOCONSTRUCCION_DDB_CCLOTE(Integer ANIOCONSTRUCCION_DDB_CCLOTE) {
        this.ANIOCONSTRUCCION_DDB_CCLOTE = ANIOCONSTRUCCION_DDB_CCLOTE;
    }

    public Integer getANIORESTAURACION_DDB_CCLOTE() {
        return ANIORESTAURACION_DDB_CCLOTE;
    }

    public void setANIORESTAURACION_DDB_CCLOTE(Integer ANIORESTAURACION_DDB_CCLOTE) {
        this.ANIORESTAURACION_DDB_CCLOTE = ANIORESTAURACION_DDB_CCLOTE;
    }

    public float getAREACONSTRUIDA_DDB_CCLOTE() {
        return AREACONSTRUIDA_DDB_CCLOTE;
    }

    public void setAREACONSTRUIDA_DDB_CCLOTE(float AREACONSTRUIDA_DDB_CCLOTE) {
        this.AREACONSTRUIDA_DDB_CCLOTE = AREACONSTRUIDA_DDB_CCLOTE;
    }

    public String getUSOCONSTRUCTIVOPISO_DDB_CCLOTE() {
        return USOCONSTRUCTIVOPISO_DDB_CCLOTE;
    }

    public void setUSOCONSTRUCTIVOPISO_DDB_CCLOTE(String USOCONSTRUCTIVOPISO_DDB_CCLOTE) {
        this.USOCONSTRUCTIVOPISO_DDB_CCLOTE = USOCONSTRUCTIVOPISO_DDB_CCLOTE;
    }
    
    

}
