/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.desgo.modelo;

/**
 *
 * @author egct
 */
public class DatosDUnidad_VCLote {
    Integer ID_DDU_VCLOTE;
    String LASIFICACIONVIVIENDA_DDU_VCLOTE;
    String TIPODOCUMENTO_DDU_VCLOTE;
    String TIPOVIVIENDA_DDU_VCLOTE;
    String CONDICIONOCUPACION_DDU_VCLOTE;
    String DESCRIPCIONDOCIDEN_DDU_VCLOTE;
    String APJEFEHGAR_DDU_VCLOTE;

    public DatosDUnidad_VCLote() {
    }

    public DatosDUnidad_VCLote(Integer ID_DDU_VCLOTE, String LASIFICACIONVIVIENDA_DDU_VCLOTE, String TIPODOCUMENTO_DDU_VCLOTE, String TIPOVIVIENDA_DDU_VCLOTE, String CONDICIONOCUPACION_DDU_VCLOTE, String DESCRIPCIONDOCIDEN_DDU_VCLOTE, String APJEFEHGAR_DDU_VCLOTE) {
        this.ID_DDU_VCLOTE = ID_DDU_VCLOTE;
        this.LASIFICACIONVIVIENDA_DDU_VCLOTE = LASIFICACIONVIVIENDA_DDU_VCLOTE;
        this.TIPODOCUMENTO_DDU_VCLOTE = TIPODOCUMENTO_DDU_VCLOTE;
        this.TIPOVIVIENDA_DDU_VCLOTE = TIPOVIVIENDA_DDU_VCLOTE;
        this.CONDICIONOCUPACION_DDU_VCLOTE = CONDICIONOCUPACION_DDU_VCLOTE;
        this.DESCRIPCIONDOCIDEN_DDU_VCLOTE = DESCRIPCIONDOCIDEN_DDU_VCLOTE;
        this.APJEFEHGAR_DDU_VCLOTE = APJEFEHGAR_DDU_VCLOTE;
    }

    public Integer getID_DDU_VCLOTE() {
        return ID_DDU_VCLOTE;
    }

    public void setID_DDU_VCLOTE(Integer ID_DDU_VCLOTE) {
        this.ID_DDU_VCLOTE = ID_DDU_VCLOTE;
    }

    public String getLASIFICACIONVIVIENDA_DDU_VCLOTE() {
        return LASIFICACIONVIVIENDA_DDU_VCLOTE;
    }

    public void setLASIFICACIONVIVIENDA_DDU_VCLOTE(String LASIFICACIONVIVIENDA_DDU_VCLOTE) {
        this.LASIFICACIONVIVIENDA_DDU_VCLOTE = LASIFICACIONVIVIENDA_DDU_VCLOTE;
    }

    public String getTIPODOCUMENTO_DDU_VCLOTE() {
        return TIPODOCUMENTO_DDU_VCLOTE;
    }

    public void setTIPODOCUMENTO_DDU_VCLOTE(String TIPODOCUMENTO_DDU_VCLOTE) {
        this.TIPODOCUMENTO_DDU_VCLOTE = TIPODOCUMENTO_DDU_VCLOTE;
    }

    public String getTIPOVIVIENDA_DDU_VCLOTE() {
        return TIPOVIVIENDA_DDU_VCLOTE;
    }

    public void setTIPOVIVIENDA_DDU_VCLOTE(String TIPOVIVIENDA_DDU_VCLOTE) {
        this.TIPOVIVIENDA_DDU_VCLOTE = TIPOVIVIENDA_DDU_VCLOTE;
    }

    public String getCONDICIONOCUPACION_DDU_VCLOTE() {
        return CONDICIONOCUPACION_DDU_VCLOTE;
    }

    public void setCONDICIONOCUPACION_DDU_VCLOTE(String CONDICIONOCUPACION_DDU_VCLOTE) {
        this.CONDICIONOCUPACION_DDU_VCLOTE = CONDICIONOCUPACION_DDU_VCLOTE;
    }

    public String getDESCRIPCIONDOCIDEN_DDU_VCLOTE() {
        return DESCRIPCIONDOCIDEN_DDU_VCLOTE;
    }

    public void setDESCRIPCIONDOCIDEN_DDU_VCLOTE(String DESCRIPCIONDOCIDEN_DDU_VCLOTE) {
        this.DESCRIPCIONDOCIDEN_DDU_VCLOTE = DESCRIPCIONDOCIDEN_DDU_VCLOTE;
    }

    public String getAPJEFEHGAR_DDU_VCLOTE() {
        return APJEFEHGAR_DDU_VCLOTE;
    }

    public void setAPJEFEHGAR_DDU_VCLOTE(String APJEFEHGAR_DDU_VCLOTE) {
        this.APJEFEHGAR_DDU_VCLOTE = APJEFEHGAR_DDU_VCLOTE;
    }
     

}
