/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.desgo.modelo;

/**
 *
 * @author egct
 */
public class InstalacionNivelV_VCLote {
    Integer ID_INV_VCLOTE;
    String ACABADOPISO_INV_VCLOTE;
    String EACABADOPISO_INV_VCLOTE;
    String AGUAP_INV_VCLOTE;
    String AGUAR_INV_VCLOTE;
    String EEXCRETAS_INV_VCLOTE;
    String ENERGIAEP_INV_VCLOTE;
    String ELIMINACIONBASURA_INV_VCLOTE;
    String TENENCIAVIVIENDA_INV_VCLOTE;
    Integer NUMEROHABITACION_INV_VCLOTE;
    Integer NUMERODORMITORIO_INV_VCLOTE;
    Integer ESPACIODUCHARSE_INV_VCLOTE;
    Integer NUMEROHABITANTES;
    Integer NUMEROHOGARES_INV_VCLOTE;
    Boolean TELEFONOCONVENCIONAL_INV_VCLOTE;
    Integer NUMEROCELULARES_INV_VCLOTE;
    Integer SERVICIOINTERNET_INV_VCLOTE;

    public InstalacionNivelV_VCLote() {
    }

    public InstalacionNivelV_VCLote(Integer ID_INV_VCLOTE, String ACABADOPISO_INV_VCLOTE, String EACABADOPISO_INV_VCLOTE, String AGUAP_INV_VCLOTE, String AGUAR_INV_VCLOTE, String EEXCRETAS_INV_VCLOTE, String ENERGIAEP_INV_VCLOTE, String ELIMINACIONBASURA_INV_VCLOTE, String TENENCIAVIVIENDA_INV_VCLOTE, Integer NUMEROHABITACION_INV_VCLOTE, Integer NUMERODORMITORIO_INV_VCLOTE, Integer ESPACIODUCHARSE_INV_VCLOTE, Integer NUMEROHABITANTES, Integer NUMEROHOGARES_INV_VCLOTE, Boolean TELEFONOCONVENCIONAL_INV_VCLOTE, Integer NUMEROCELULARES_INV_VCLOTE, Integer SERVICIOINTERNET_INV_VCLOTE) {
        this.ID_INV_VCLOTE = ID_INV_VCLOTE;
        this.ACABADOPISO_INV_VCLOTE = ACABADOPISO_INV_VCLOTE;
        this.EACABADOPISO_INV_VCLOTE = EACABADOPISO_INV_VCLOTE;
        this.AGUAP_INV_VCLOTE = AGUAP_INV_VCLOTE;
        this.AGUAR_INV_VCLOTE = AGUAR_INV_VCLOTE;
        this.EEXCRETAS_INV_VCLOTE = EEXCRETAS_INV_VCLOTE;
        this.ENERGIAEP_INV_VCLOTE = ENERGIAEP_INV_VCLOTE;
        this.ELIMINACIONBASURA_INV_VCLOTE = ELIMINACIONBASURA_INV_VCLOTE;
        this.TENENCIAVIVIENDA_INV_VCLOTE = TENENCIAVIVIENDA_INV_VCLOTE;
        this.NUMEROHABITACION_INV_VCLOTE = NUMEROHABITACION_INV_VCLOTE;
        this.NUMERODORMITORIO_INV_VCLOTE = NUMERODORMITORIO_INV_VCLOTE;
        this.ESPACIODUCHARSE_INV_VCLOTE = ESPACIODUCHARSE_INV_VCLOTE;
        this.NUMEROHABITANTES = NUMEROHABITANTES;
        this.NUMEROHOGARES_INV_VCLOTE = NUMEROHOGARES_INV_VCLOTE;
        this.TELEFONOCONVENCIONAL_INV_VCLOTE = TELEFONOCONVENCIONAL_INV_VCLOTE;
        this.NUMEROCELULARES_INV_VCLOTE = NUMEROCELULARES_INV_VCLOTE;
        this.SERVICIOINTERNET_INV_VCLOTE = SERVICIOINTERNET_INV_VCLOTE;
    }

    public Integer getID_INV_VCLOTE() {
        return ID_INV_VCLOTE;
    }

    public void setID_INV_VCLOTE(Integer ID_INV_VCLOTE) {
        this.ID_INV_VCLOTE = ID_INV_VCLOTE;
    }

    public String getACABADOPISO_INV_VCLOTE() {
        return ACABADOPISO_INV_VCLOTE;
    }

    public void setACABADOPISO_INV_VCLOTE(String ACABADOPISO_INV_VCLOTE) {
        this.ACABADOPISO_INV_VCLOTE = ACABADOPISO_INV_VCLOTE;
    }

    public String getEACABADOPISO_INV_VCLOTE() {
        return EACABADOPISO_INV_VCLOTE;
    }

    public void setEACABADOPISO_INV_VCLOTE(String EACABADOPISO_INV_VCLOTE) {
        this.EACABADOPISO_INV_VCLOTE = EACABADOPISO_INV_VCLOTE;
    }

    public String getAGUAP_INV_VCLOTE() {
        return AGUAP_INV_VCLOTE;
    }

    public void setAGUAP_INV_VCLOTE(String AGUAP_INV_VCLOTE) {
        this.AGUAP_INV_VCLOTE = AGUAP_INV_VCLOTE;
    }

    public String getAGUAR_INV_VCLOTE() {
        return AGUAR_INV_VCLOTE;
    }

    public void setAGUAR_INV_VCLOTE(String AGUAR_INV_VCLOTE) {
        this.AGUAR_INV_VCLOTE = AGUAR_INV_VCLOTE;
    }

    public String getEEXCRETAS_INV_VCLOTE() {
        return EEXCRETAS_INV_VCLOTE;
    }

    public void setEEXCRETAS_INV_VCLOTE(String EEXCRETAS_INV_VCLOTE) {
        this.EEXCRETAS_INV_VCLOTE = EEXCRETAS_INV_VCLOTE;
    }

    public String getENERGIAEP_INV_VCLOTE() {
        return ENERGIAEP_INV_VCLOTE;
    }

    public void setENERGIAEP_INV_VCLOTE(String ENERGIAEP_INV_VCLOTE) {
        this.ENERGIAEP_INV_VCLOTE = ENERGIAEP_INV_VCLOTE;
    }

    public String getELIMINACIONBASURA_INV_VCLOTE() {
        return ELIMINACIONBASURA_INV_VCLOTE;
    }

    public void setELIMINACIONBASURA_INV_VCLOTE(String ELIMINACIONBASURA_INV_VCLOTE) {
        this.ELIMINACIONBASURA_INV_VCLOTE = ELIMINACIONBASURA_INV_VCLOTE;
    }

    public String getTENENCIAVIVIENDA_INV_VCLOTE() {
        return TENENCIAVIVIENDA_INV_VCLOTE;
    }

    public void setTENENCIAVIVIENDA_INV_VCLOTE(String TENENCIAVIVIENDA_INV_VCLOTE) {
        this.TENENCIAVIVIENDA_INV_VCLOTE = TENENCIAVIVIENDA_INV_VCLOTE;
    }

    public Integer getNUMEROHABITACION_INV_VCLOTE() {
        return NUMEROHABITACION_INV_VCLOTE;
    }

    public void setNUMEROHABITACION_INV_VCLOTE(Integer NUMEROHABITACION_INV_VCLOTE) {
        this.NUMEROHABITACION_INV_VCLOTE = NUMEROHABITACION_INV_VCLOTE;
    }

    public Integer getNUMERODORMITORIO_INV_VCLOTE() {
        return NUMERODORMITORIO_INV_VCLOTE;
    }

    public void setNUMERODORMITORIO_INV_VCLOTE(Integer NUMERODORMITORIO_INV_VCLOTE) {
        this.NUMERODORMITORIO_INV_VCLOTE = NUMERODORMITORIO_INV_VCLOTE;
    }

    public Integer getESPACIODUCHARSE_INV_VCLOTE() {
        return ESPACIODUCHARSE_INV_VCLOTE;
    }

    public void setESPACIODUCHARSE_INV_VCLOTE(Integer ESPACIODUCHARSE_INV_VCLOTE) {
        this.ESPACIODUCHARSE_INV_VCLOTE = ESPACIODUCHARSE_INV_VCLOTE;
    }

    public Integer getNUMEROHABITANTES() {
        return NUMEROHABITANTES;
    }

    public void setNUMEROHABITANTES(Integer NUMEROHABITANTES) {
        this.NUMEROHABITANTES = NUMEROHABITANTES;
    }

    public Integer getNUMEROHOGARES_INV_VCLOTE() {
        return NUMEROHOGARES_INV_VCLOTE;
    }

    public void setNUMEROHOGARES_INV_VCLOTE(Integer NUMEROHOGARES_INV_VCLOTE) {
        this.NUMEROHOGARES_INV_VCLOTE = NUMEROHOGARES_INV_VCLOTE;
    }

    public Boolean getTELEFONOCONVENCIONAL_INV_VCLOTE() {
        return TELEFONOCONVENCIONAL_INV_VCLOTE;
    }

    public void setTELEFONOCONVENCIONAL_INV_VCLOTE(Boolean TELEFONOCONVENCIONAL_INV_VCLOTE) {
        this.TELEFONOCONVENCIONAL_INV_VCLOTE = TELEFONOCONVENCIONAL_INV_VCLOTE;
    }

    public Integer getNUMEROCELULARES_INV_VCLOTE() {
        return NUMEROCELULARES_INV_VCLOTE;
    }

    public void setNUMEROCELULARES_INV_VCLOTE(Integer NUMEROCELULARES_INV_VCLOTE) {
        this.NUMEROCELULARES_INV_VCLOTE = NUMEROCELULARES_INV_VCLOTE;
    }

    public Integer getSERVICIOINTERNET_INV_VCLOTE() {
        return SERVICIOINTERNET_INV_VCLOTE;
    }

    public void setSERVICIOINTERNET_INV_VCLOTE(Integer SERVICIOINTERNET_INV_VCLOTE) {
        this.SERVICIOINTERNET_INV_VCLOTE = SERVICIOINTERNET_INV_VCLOTE;
    }
    
    

}
