/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.com.desgo.modelo;

import java.util.Date;

/**
 *
 * @author egct
 */
public class ResponsablesLote {
    Integer ID_RLOTE;
    String ACTUALIZADORCEDULAPASAPORTE_RLOTE;
    Date ACTUALIZADORFECHA_RLOTE;
    String ACTUALIZADORFIRMA_RLOTE;
    String FISCALIZADORCEDULAPASAPORTE_RLOTE;
    Date FISCALIZADORFECHA_RLOTE;
    String FISCALIZADORFIRMA_RLOTE;

    public ResponsablesLote() {
    }

    public ResponsablesLote(Integer ID_RLOTE, String ACTUALIZADORCEDULAPASAPORTE_RLOTE, Date ACTUALIZADORFECHA_RLOTE, String ACTUALIZADORFIRMA_RLOTE, String FISCALIZADORCEDULAPASAPORTE_RLOTE, Date FISCALIZADORFECHA_RLOTE, String FISCALIZADORFIRMA_RLOTE) {
        this.ID_RLOTE = ID_RLOTE;
        this.ACTUALIZADORCEDULAPASAPORTE_RLOTE = ACTUALIZADORCEDULAPASAPORTE_RLOTE;
        this.ACTUALIZADORFECHA_RLOTE = ACTUALIZADORFECHA_RLOTE;
        this.ACTUALIZADORFIRMA_RLOTE = ACTUALIZADORFIRMA_RLOTE;
        this.FISCALIZADORCEDULAPASAPORTE_RLOTE = FISCALIZADORCEDULAPASAPORTE_RLOTE;
        this.FISCALIZADORFECHA_RLOTE = FISCALIZADORFECHA_RLOTE;
        this.FISCALIZADORFIRMA_RLOTE = FISCALIZADORFIRMA_RLOTE;
    }

    public Integer getID_RLOTE() {
        return ID_RLOTE;
    }

    public void setID_RLOTE(Integer ID_RLOTE) {
        this.ID_RLOTE = ID_RLOTE;
    }

    public String getACTUALIZADORCEDULAPASAPORTE_RLOTE() {
        return ACTUALIZADORCEDULAPASAPORTE_RLOTE;
    }

    public void setACTUALIZADORCEDULAPASAPORTE_RLOTE(String ACTUALIZADORCEDULAPASAPORTE_RLOTE) {
        this.ACTUALIZADORCEDULAPASAPORTE_RLOTE = ACTUALIZADORCEDULAPASAPORTE_RLOTE;
    }

    public Date getACTUALIZADORFECHA_RLOTE() {
        return ACTUALIZADORFECHA_RLOTE;
    }

    public void setACTUALIZADORFECHA_RLOTE(Date ACTUALIZADORFECHA_RLOTE) {
        this.ACTUALIZADORFECHA_RLOTE = ACTUALIZADORFECHA_RLOTE;
    }

    public String getACTUALIZADORFIRMA_RLOTE() {
        return ACTUALIZADORFIRMA_RLOTE;
    }

    public void setACTUALIZADORFIRMA_RLOTE(String ACTUALIZADORFIRMA_RLOTE) {
        this.ACTUALIZADORFIRMA_RLOTE = ACTUALIZADORFIRMA_RLOTE;
    }

    public String getFISCALIZADORCEDULAPASAPORTE_RLOTE() {
        return FISCALIZADORCEDULAPASAPORTE_RLOTE;
    }

    public void setFISCALIZADORCEDULAPASAPORTE_RLOTE(String FISCALIZADORCEDULAPASAPORTE_RLOTE) {
        this.FISCALIZADORCEDULAPASAPORTE_RLOTE = FISCALIZADORCEDULAPASAPORTE_RLOTE;
    }

    public Date getFISCALIZADORFECHA_RLOTE() {
        return FISCALIZADORFECHA_RLOTE;
    }

    public void setFISCALIZADORFECHA_RLOTE(Date FISCALIZADORFECHA_RLOTE) {
        this.FISCALIZADORFECHA_RLOTE = FISCALIZADORFECHA_RLOTE;
    }

    public String getFISCALIZADORFIRMA_RLOTE() {
        return FISCALIZADORFIRMA_RLOTE;
    }

    public void setFISCALIZADORFIRMA_RLOTE(String FISCALIZADORFIRMA_RLOTE) {
        this.FISCALIZADORFIRMA_RLOTE = FISCALIZADORFIRMA_RLOTE;
    }

    
}
